CREATE TABLE IF NOT EXISTS signals (
  room TEXT NOT NULL,
  id TEXT NOT NULL,
  kind TEXT NOT NULL,
  box TEXT NOT NULL,
  at INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS signals_room ON signals (room, kind, at);
CREATE TABLE IF NOT EXISTS rooms (
  room TEXT PRIMARY KEY,
  seen INTEGER NOT NULL
);
